### ISSUE TITLE
How can I run this on windows?

### ISSUE THREAD

**Issue by mackcusk** [ElegyD/nvidia-notifier#1]

**Comment by ElegyD** [comment]
Download & install Git from [here](https://git-scm.com/download/win). You can take the 64-bit version probably.
Download & install Node from [here](https://nodejs.org/). Take the LTS version.
Open the command prompt and navigate to where you want to have the project running.
Follow the [Installation](https://github.com/ElegyD/nvidia-notifier#installation) from the README.
