### ISSUE TITLE
Zlib Error: incorrect header check

### ISSUE THREAD

**Issue by MartinJourjon** [ElegyD/nvidia-notifier#2]
Hello,
I tried to use your bot, you did a super job, however I have an error at start,

> Error: incorrect header check
    at Zlib.zlibOnError [as onerror] (node:zlib:190:17) {
  errno: -3,
  code: 'Z_DATA_ERROR'
}

I had other issues on the GPU selection I had to put manually true in the code.

Do you have an idea ? Did you updated things ?

**Comment by ElegyD** [comment]
Hey, sorry for the late reply.
I've seen this error before, but only a few times while running for several days and not immediately on start.
It has something to do with the gzip encoding which should be handled by zlib in the [`fetchFEInventory`](https://github.com/ElegyD/nvidia-notifier/blob/1e3d4c13ed0460cfd251ff816d7a77ace9cf90a1/index.js#L422) and [`fetchProductDetails`](https://github.com/ElegyD/nvidia-notifier/blob/1e3d4c13ed0460cfd251ff816d7a77ace9cf90a1/index.js#L449) functions.
Haven't been able to fix this yet, I have to take another look at this.

Regarding GPU selection, check the [Setup environment variables](https://github.com/ElegyD/nvidia-notifier#setup-environment-variables) step in the README.
Copy all the variables from the README to the `.env` file and set the value to `true` on the cards you want to have enabled.

**Comment by ElegyD** [comment]
Hi again,
I may have fixed this with the last commit f3069d88349a3d4f717a2c8a24a3473c83778913.
Turns out we can call the API without the Accept-Encoding header so I removed the encoding.
But I have to keep monitoring it.
Make sure to update the script with `git pull` (and `npm install` to update dependencies).
